### ISSUE TITLE
Task: Feedback on additional info from intake

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-functions#10]
### Description

The following feedback was provided on additional information that can be added from the intake form.

### Tasks

- [ ] Information under “Educational History”- average/below average/above average student and what grades they receive mostly
- [ ] Information under “Social Functioning”- we ask parents to include positive adjectives to describe their child, how many friends they have, hobbies/interests.
- [x] Information regarding hearing device (under medical history: He does/does not require a hearing device). Resolved by #11
- [ ] Information regarding current psychiatric medications (the very last section of purple, under the header “Current Psychiatric Functioning”)

**Comment by ReinderVosDeWael** [comment]
Feedback moved to sharepoint
