### ISSUE TITLE
Spike: Assess the time and cost differential of running a separate LanguageTool Function 

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-functions#31]
### Description

At present, a large chunk of the intake form's runtime is due to LanguageTool. This might go a lot faster if we use a dedicated Azure function for languagetool, and ping that from the Python function. 

### Tasks

- [ ] Build a LanguageTool Azure Function.
- [ ] Hook up CTK functions to this tool.
- [ ] Assess whether there are appreciable speed gains. 

### Freeform Notes

This spike is capped at 2 working days.
