### ISSUE TITLE
Task: Run integrations tests with real data on Azure Pipelines

### ISSUE THREAD

**Issue by ReinderVosDeWael** [childmindresearch/ctk-functions#90]
### Description

To ensure that any new deployment runs without error, integration tests should be performed with real data. As this is protected data, it should run within a BAA-protected environment.

### Tasks

- [x] Ascertain Azure DevOps is protected under our Azure BAA.
- [x] Set up integration tests with at least three subjects in Azure DevOps. 
- [ ] Deploy only if these tests succeed.
